# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c1cbbd2f841162d11a8c94e0fd4287a792d927d4d5636d6f05b3ce7b93a0e755f7ddfb7fe916203bfb840d2aa34e01198e5783787fd35953b98e6c019a7d72

test:
  secret_key_base: a51c77a3d99818fd97f847e1ad0dd5f56266f617287f3b0901f147fb79eb9b89e462c62fbb308752f55f95a2fb27a8458348b3fd4c156933b97a92eeba9afa77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
